### ISSUE TITLE
Petit problème image site dev

### ISSUE THREAD

**Issue by Pierre-Gilles** [piznel/gladys-livebox#1]
Hello! 

Je viens de publish ton module sur le site dev. Beau boulot! :)

Il y a une image qui pète au niveau du responsive, si tu peux juste fixer ça et ensuite je le valide pour distribution sur instance ;) 

https://developer.gladysassistant.com/fr/modules/livebox

**Comment by piznel** [comment]
Salut,

Normalement, c'est corrigé :)

**Comment by Pierre-Gilles** [comment]
Top! C'est published sur les instances :)
